export default [
  {
    type: 'style',
    name: 'outline',
    title: 'Outline',
    children: [
      {
        type: 'category',
        name: 'Navigation',
        title: 'Navigation',
        children: [
          { type: 'component', title: 'Home', name: 'HomeIcon' },
          { type: 'component', title: 'Apps', name: 'AppsIcon' },
          { type: 'component', title: 'TriangleDown', name: 'TriangleDownIcon' },
          { type: 'component', title: 'TriangleLeft', name: 'TriangleLeftIcon' },
          { type: 'component', title: 'TriangleRight', name: 'TriangleRightIcon' },
          { type: 'component', title: 'ShellWindowMaximize', name: 'ShellWindowMaximizeIcon' },
          { type: 'component', title: 'TriangleUp', name: 'TriangleUpIcon' },
          { type: 'component', title: 'Sort', name: 'SortIcon' },
          { type: 'component', title: 'Up', name: 'UpIcon' },
          { type: 'component', title: 'Down', name: 'DownIcon' },
          { type: 'component', title: 'Left', name: 'LeftIcon' },
          { type: 'component', title: 'Right', name: 'RightIcon' },
          { type: 'component', title: 'DoubleArrowUp', name: 'DoubleArrowUpIcon' },
          { type: 'component', title: 'DoubleArrowDown', name: 'DoubleArrowDownIcon' },
          { type: 'component', title: 'DoubleArrowLeft', name: 'DoubleArrowLeftIcon' },
          { type: 'component', title: 'DoubleArrowRight', name: 'DoubleArrowRightIcon' },
          { type: 'component', title: 'ArrowUp', name: 'ArrowUpIcon' },
          { type: 'component', title: 'ArrowDown', name: 'ArrowDownIcon' },
          { type: 'component', title: 'ArrowLeft', name: 'ArrowLeftIcon' },
          { type: 'component', title: 'MenuThwartwise', name: 'MenuThwartwiseIcon' },
          { type: 'component', title: 'Menu2', name: 'Menu2Icon' },
          { type: 'component', title: 'ArrowRight', name: 'ArrowRightIcon' },
          { type: 'component', title: 'MenuEndways', name: 'MenuEndwaysIcon' },
          { type: 'component', title: 'CloseSmall', name: 'CloseSmallIcon' },
          { type: 'component', title: 'OpenNew', name: 'OpenNewIcon' },
          { type: 'component', title: 'ShellWindowMinimize', name: 'ShellWindowMinimizeIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Notice',
        title: 'Notice',
        children: [
          { type: 'component', title: 'RemindClose', name: 'RemindCloseIcon' },
          { type: 'component', title: 'WifiAbnormal', name: 'WifiAbnormalIcon' },
          { type: 'component', title: 'Question', name: 'QuestionIcon' },
          { type: 'component', title: 'Remind', name: 'RemindIcon' },
          { type: 'component', title: 'AddOne', name: 'AddOneIcon' },
          { type: 'component', title: 'Check', name: 'CheckIcon' },
          { type: 'component', title: 'CircleMore', name: 'CircleMoreIcon' },
          { type: 'component', title: 'More', name: 'MoreIcon' },
          { type: 'component', title: 'Minus', name: 'MinusIcon' },
          { type: 'component', title: 'CircleAdd', name: 'CircleAddIcon' },
          { type: 'component', title: 'TriangleWarning', name: 'TriangleWarningIcon' },
          { type: 'component', title: 'Exclamation', name: 'ExclamationIcon' },
          { type: 'component', title: 'CircleInformation', name: 'CircleInformationIcon' },
          { type: 'component', title: 'CircleClose', name: 'CircleCloseIcon' },
          { type: 'component', title: 'CircleStar', name: 'CircleStarIcon' },
          { type: 'component', title: 'CircleSucceed', name: 'CircleSucceedIcon' },
          { type: 'component', title: 'CircleWarning', name: 'CircleWarningIcon' },
          { type: 'component', title: 'Star', name: 'StarIcon' },
          { type: 'component', title: 'CircleHelp', name: 'CircleHelpIcon' },
          { type: 'component', title: 'Disable', name: 'DisableIcon' },
          { type: 'component', title: 'Wifi', name: 'WifiIcon' },
          { type: 'component', title: 'WifiClose', name: 'WifiCloseIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Action',
        title: 'Action',
        children: [
          { type: 'component', title: 'MoveUp', name: 'MoveUpIcon' },
          { type: 'component', title: 'MoveDown', name: 'MoveDownIcon' },
          { type: 'component', title: 'Undo', name: 'UndoIcon' },
          { type: 'component', title: 'Clear', name: 'ClearIcon' },
          { type: 'component', title: 'Pin', name: 'PinIcon' },
          { type: 'component', title: 'ThumbDown', name: 'ThumbDownIcon' },
          { type: 'component', title: 'ThumbUp', name: 'ThumbUpIcon' },
          { type: 'component', title: 'Send', name: 'SendIcon' },
          { type: 'component', title: 'ViewOff', name: 'ViewOffIcon' },
          { type: 'component', title: 'InfuseOne', name: 'InfuseOneIcon' },
          { type: 'component', title: 'Download', name: 'DownloadIcon' },
          { type: 'component', title: 'ToTop', name: 'ToTopIcon' },
          { type: 'component', title: 'ToBottom', name: 'ToBottomIcon' },
          { type: 'component', title: 'Link', name: 'LinkIcon' },
          { type: 'component', title: 'MapLocation', name: 'MapLocationIcon' },
          { type: 'component', title: 'Drag', name: 'DragIcon' },
          { type: 'component', title: 'Refresh', name: 'RefreshIcon' },
          { type: 'component', title: 'RefreshDoing', name: 'RefreshDoingIcon' },
          { type: 'component', title: 'RefreshDone', name: 'RefreshDoneIcon' },
          { type: 'component', title: 'Scan', name: 'ScanIcon' },
          { type: 'component', title: 'Switch', name: 'SwitchIcon' },
          { type: 'component', title: 'Unlink', name: 'UnlinkIcon' },
          { type: 'component', title: 'Control', name: 'ControlIcon' },
          { type: 'component', title: 'Decorate', name: 'DecorateIcon' },
          { type: 'component', title: 'FormatPainter', name: 'FormatPainterIcon' },
          { type: 'component', title: 'CopyOne', name: 'CopyOneIcon' },
          { type: 'component', title: 'Delete', name: 'DeleteIcon' },
          { type: 'component', title: 'Share', name: 'ShareIcon' },
          { type: 'component', title: 'SettingSearch', name: 'SettingSearchIcon' },
          { type: 'component', title: 'Setting', name: 'SettingIcon' },
          { type: 'component', title: 'Swerve', name: 'SwerveIcon' },
          { type: 'component', title: 'Save', name: 'SaveIcon' },
          { type: 'component', title: 'Print', name: 'PrintIcon' },
          { type: 'component', title: 'Power', name: 'PowerIcon' },
          { type: 'component', title: 'AmountUpTwo', name: 'AmountUpTwoIcon' },
          { type: 'component', title: 'AmountDownTwo', name: 'AmountDownTwoIcon' },
          { type: 'component', title: 'Checkbox', name: 'CheckboxIcon' },
          { type: 'component', title: 'CheckCorrect', name: 'CheckCorrectIcon' },
          { type: 'component', title: 'CheckDisabled', name: 'CheckDisabledIcon' },
          { type: 'component', title: 'RadioUnselected', name: 'RadioUnselectedIcon' },
          { type: 'component', title: 'RadioSelected', name: 'RadioSelectedIcon' },
          { type: 'component', title: 'SaveAs', name: 'SaveAsIcon' },
          { type: 'component', title: 'Uploading', name: 'UploadingIcon' },
          { type: 'component', title: 'Translate', name: 'TranslateIcon' },
          { type: 'component', title: 'Paste', name: 'PasteIcon' },
          { type: 'component', title: 'Export', name: 'ExportIcon' },
          { type: 'component', title: 'Phone', name: 'PhoneIcon' },
          { type: 'component', title: 'InfuseTwo', name: 'InfuseTwoIcon' },
          { type: 'component', title: 'ExportTwo', name: 'ExportTwoIcon' },
          { type: 'component', title: 'BatchCheck', name: 'BatchCheckIcon' },
          { type: 'component', title: 'Rollback', name: 'RollbackIcon' },
          { type: 'component', title: 'Top', name: 'TopIcon' },
          { type: 'component', title: 'Goto', name: 'GotoIcon' },
          { type: 'component', title: 'AmountUp', name: 'AmountUpIcon' },
          { type: 'component', title: 'AmountDown', name: 'AmountDownIcon' },
          { type: 'component', title: 'Submit', name: 'SubmitIcon' },
          { type: 'component', title: 'AddChat', name: 'AddChatIcon' },
          { type: 'component', title: 'AddChatTwo', name: 'AddChatTwoIcon' },
          { type: 'component', title: 'SortDefault', name: 'SortDefaultIcon' },
          { type: 'component', title: 'SortA2Z', name: 'SortA2ZIcon' },
          { type: 'component', title: 'SortZ2A', name: 'SortZ2AIcon' },
          { type: 'component', title: 'PinPre', name: 'PinPreIcon' },
          { type: 'component', title: 'View', name: 'ViewIcon' },
          { type: 'component', title: 'Filter', name: 'FilterIcon' },
          { type: 'component', title: 'Search', name: 'SearchIcon' },
          { type: 'component', title: 'Urgency', name: 'UrgencyIcon' },
          { type: 'component', title: 'Clothes', name: 'ClothesIcon' },
          { type: 'component', title: 'Microphone', name: 'MicrophoneIcon' },
          { type: 'component', title: 'BatchAdd', name: 'BatchAddIcon' },
        ],
      },
      {
        type: 'category',
        name: 'control',
        title: 'Control',
        children: [
          { type: 'component', title: 'ScreenFull', name: 'ScreenFullIcon' },
          { type: 'component', title: 'ScreenOff', name: 'ScreenOffIcon' },
          { type: 'component', title: 'Move', name: 'MoveIcon' },
          { type: 'component', title: 'Pointer', name: 'PointerIcon' },
          { type: 'component', title: 'Coverage', name: 'CoverageIcon' },
          { type: 'component', title: 'SurfaceTop', name: 'SurfaceTopIcon' },
          { type: 'component', title: 'SurfaceLeft', name: 'SurfaceLeftIcon' },
          { type: 'component', title: 'SurfaceRight', name: 'SurfaceRightIcon' },
          { type: 'component', title: 'Anticlockwise90', name: 'Anticlockwise90Icon' },
          { type: 'component', title: 'CopyTwo', name: 'CopyTwoIcon' },
          { type: 'component', title: 'AdjustHight', name: 'AdjustHightIcon' },
          { type: 'component', title: 'HightLessen', name: 'HightLessenIcon' },
          { type: 'component', title: 'AdjustWidth', name: 'AdjustWidthIcon' },
          { type: 'component', title: 'VerticalSplit', name: 'VerticalSplitIcon' },
          { type: 'component', title: 'VerticalCenter', name: 'VerticalCenterIcon' },
          { type: 'component', title: 'CenterHorizontally', name: 'CenterHorizontallyIcon' },
          { type: 'component', title: 'TopAlign', name: 'TopAlignIcon' },
          { type: 'component', title: 'BottomAlign', name: 'BottomAlignIcon' },
          { type: 'component', title: 'FrontSquare', name: 'FrontSquareIcon' },
          { type: 'component', title: 'BackSquare', name: 'BackSquareIcon' },
          { type: 'component', title: 'LeftSquare', name: 'LeftSquareIcon' },
          { type: 'component', title: 'RightSquare', name: 'RightSquareIcon' },
          { type: 'component', title: 'Text', name: 'TextIcon' },
          { type: 'component', title: 'Keyboard', name: 'KeyboardIcon' },
          { type: 'component', title: 'ZoomOut', name: 'ZoomOutIcon' },
          { type: 'component', title: 'ZoomIn', name: 'ZoomInIcon' },
          { type: 'component', title: 'Volume', name: 'VolumeIcon' },
          { type: 'component', title: 'VolumeUp', name: 'VolumeUpIcon' },
          { type: 'component', title: 'VolumeDown', name: 'VolumeDownIcon' },
          { type: 'component', title: 'Play', name: 'PlayIcon' },
          { type: 'component', title: 'Stop', name: 'StopIcon' },
          { type: 'component', title: 'Suspend', name: 'SuspendIcon' },
          { type: 'component', title: 'FitScreen', name: 'FitScreenIcon' },
          { type: 'component', title: 'RotationLeft', name: 'RotationLeftIcon' },
          { type: 'component', title: 'RotationRight', name: 'RotationRightIcon' },
          { type: 'component', title: 'OneToOne', name: 'OneToOneIcon' },
          { type: 'component', title: 'AlignTxtBoth', name: 'AlignTxtBothIcon' },
          { type: 'component', title: 'AlignTxtLeft', name: 'AlignTxtLeftIcon' },
          { type: 'component', title: 'AlignTxtRight', name: 'AlignTxtRightIcon' },
          { type: 'component', title: 'AlignTxtCenter', name: 'AlignTxtCenterIcon' },
          { type: 'component', title: 'VolumeMute', name: 'VolumeMuteIcon' },
          { type: 'component', title: 'SurfaceFront', name: 'SurfaceFrontIcon' },
          { type: 'component', title: 'DensityL', name: 'DensityLIcon' },
          { type: 'component', title: 'DensityM', name: 'DensityMIcon' },
          { type: 'component', title: 'DensityS', name: 'DensitySIcon' },
          { type: 'component', title: 'Find', name: 'FindIcon' },
          { type: 'component', title: 'RowHeightS', name: 'RowHeightSIcon' },
          { type: 'component', title: 'RowHeightM', name: 'RowHeightMIcon' },
          { type: 'component', title: 'RowHeightL', name: 'RowHeightLIcon' },
          { type: 'component', title: 'Clockwise90', name: 'Clockwise90Icon' },
        ],
      },
      {
        type: 'category',
        name: 'Data',
        title: 'Data',
        children: [
          { type: 'component', title: 'Lightning', name: 'LightningIcon' },
          { type: 'component', title: 'PieTwo', name: 'PieTwoIcon' },
          { type: 'component', title: 'Data', name: 'DataIcon' },
          { type: 'component', title: 'Percent', name: 'PercentIcon' },
          { type: 'component', title: 'LineChart', name: 'LineChartIcon' },
          { type: 'component', title: 'Tree', name: 'TreeIcon' },
          { type: 'component', title: 'ThermoDynamic', name: 'ThermoDynamicIcon' },
          { type: 'component', title: 'Measure', name: 'MeasureIcon' },
          { type: 'component', title: 'Compiling', name: 'CompilingIcon' },
          { type: 'component', title: 'AreaChart', name: 'AreaChartIcon' },
          { type: 'component', title: 'Bar', name: 'BarIcon' },
          { type: 'component', title: 'Column', name: 'ColumnIcon' },
          { type: 'component', title: 'ColumnLine', name: 'ColumnLineIcon' },
          { type: 'component', title: 'WordCloud', name: 'WordCloudIcon' },
          { type: 'component', title: 'Table', name: 'TableIcon' },
          { type: 'component', title: 'PieOne', name: 'PieOneIcon' },
          { type: 'component', title: 'Annular', name: 'AnnularIcon' },
          { type: 'component', title: 'RadarChart', name: 'RadarChartIcon' },
          { type: 'component', title: 'DataScreen', name: 'DataScreenIcon' },
          { type: 'component', title: 'Constitute', name: 'ConstituteIcon' },
          { type: 'component', title: 'Database', name: 'DatabaseIcon' },
          { type: 'component', title: 'Decimal', name: 'DecimalIcon' },
          { type: 'component', title: 'ScatterDiagram', name: 'ScatterDiagramIcon' },
          { type: 'component', title: 'Number', name: 'NumberIcon' },
        ],
      },
      {
        type: 'category',
        name: 'common',
        title: 'Common',
        children: [
          { type: 'component', title: 'Lock', name: 'LockIcon' },
          { type: 'component', title: 'Unlock', name: 'UnlockIcon' },
          { type: 'component', title: 'SandGlass', name: 'SandGlassIcon' },
          { type: 'component', title: 'TimeOne', name: 'TimeOneIcon' },
          { type: 'component', title: 'Leaf', name: 'LeafIcon' },
          { type: 'component', title: 'PackingBox', name: 'PackingBoxIcon' },
          { type: 'component', title: 'AmountYuan', name: 'AmountYuanIcon' },
          { type: 'component', title: 'Purse', name: 'PurseIcon' },
          { type: 'component', title: 'Fire', name: 'FireIcon' },
          { type: 'component', title: 'Gift', name: 'GiftIcon' },
          { type: 'component', title: 'Label', name: 'LabelIcon' },
          { type: 'component', title: 'Location', name: 'LocationIcon' },
          { type: 'component', title: 'Park', name: 'ParkIcon' },
          { type: 'component', title: 'Hospital', name: 'HospitalIcon' },
          { type: 'component', title: 'School', name: 'SchoolIcon' },
          { type: 'component', title: 'Shopping', name: 'ShoppingIcon' },
          { type: 'component', title: 'Basket', name: 'BasketIcon' },
          { type: 'component', title: 'Berth', name: 'BerthIcon' },
          { type: 'component', title: 'Soup', name: 'SoupIcon' },
          { type: 'component', title: 'Bun', name: 'BunIcon' },
          { type: 'component', title: 'StapleFood', name: 'StapleFoodIcon' },
          { type: 'component', title: 'Bunch', name: 'BunchIcon' },
          { type: 'component', title: 'Chips', name: 'ChipsIcon' },
          { type: 'component', title: 'PlaceOrder', name: 'PlaceOrderIcon' },
          { type: 'component', title: 'Chef', name: 'ChefIcon' },
          { type: 'component', title: 'Sunny', name: 'SunnyIcon' },
          { type: 'component', title: 'Cloudy', name: 'CloudyIcon' },
          { type: 'component', title: 'LightRain', name: 'LightRainIcon' },
          { type: 'component', title: 'HeavyRain', name: 'HeavyRainIcon' },
          { type: 'component', title: 'LightSnow', name: 'LightSnowIcon' },
          { type: 'component', title: 'HeavySnow', name: 'HeavySnowIcon' },
          { type: 'component', title: 'Haze', name: 'HazeIcon' },
          { type: 'component', title: 'Sand', name: 'SandIcon' },
          { type: 'component', title: 'Music', name: 'MusicIcon' },
          { type: 'component', title: 'Mobile', name: 'MobileIcon' },
          { type: 'component', title: 'Computer', name: 'ComputerIcon' },
          { type: 'component', title: 'Building', name: 'BuildingIcon' },
          { type: 'component', title: 'Comments', name: 'CommentsIcon' },
          { type: 'component', title: 'Coupon', name: 'CouponIcon' },
          { type: 'component', title: 'Checkstand', name: 'CheckstandIcon' },
          { type: 'component', title: 'Store', name: 'StoreIcon' },
          { type: 'component', title: 'House', name: 'HouseIcon' },
          { type: 'component', title: 'Calendar', name: 'CalendarIcon' },
          { type: 'component', title: 'Stamp', name: 'StampIcon' },
          { type: 'component', title: 'Picture', name: 'PictureIcon' },
          { type: 'component', title: 'PictureOff', name: 'PictureOffIcon' },
          { type: 'component', title: 'QrCode', name: 'QrCodeIcon' },
          { type: 'component', title: 'Gather', name: 'GatherIcon' },
          { type: 'component', title: 'Puzzle', name: 'PuzzleIcon' },
          { type: 'component', title: 'BarCode', name: 'BarCodeIcon' },
          { type: 'component', title: 'Handshake', name: 'HandshakeIcon' },
          { type: 'component', title: 'Flag', name: 'FlagIcon' },
          { type: 'component', title: 'Motorcycle', name: 'MotorcycleIcon' },
          { type: 'component', title: 'Shield', name: 'ShieldIcon' },
          { type: 'component', title: 'Vip', name: 'VipIcon' },
          { type: 'component', title: 'Calculator', name: 'CalculatorIcon' },
          { type: 'component', title: 'Equipment', name: 'EquipmentIcon' },
          { type: 'component', title: 'OnlineGateway', name: 'OnlineGatewayIcon' },
          { type: 'component', title: 'OfflineGateway', name: 'OfflineGatewayIcon' },
          { type: 'component', title: 'Monitoring', name: 'MonitoringIcon' },
          { type: 'component', title: 'Promotion', name: 'PromotionIcon' },
          { type: 'component', title: 'Service', name: 'ServiceIcon' },
          { type: 'component', title: 'ShoppingCart', name: 'ShoppingCartIcon' },
          { type: 'component', title: 'Camera', name: 'CameraIcon' },
          { type: 'component', title: 'TimeTwo', name: 'TimeTwoIcon' },
          { type: 'component', title: 'Oclock', name: 'OclockIcon' },
          { type: 'component', title: 'Earth', name: 'EarthIcon' },
          { type: 'component', title: 'EmailSend', name: 'EmailSendIcon' },
          { type: 'component', title: 'PushMgt', name: 'PushMgtIcon' },
          { type: 'component', title: 'Deal', name: 'DealIcon' },
          { type: 'component', title: 'New', name: 'NewIcon' },
        ],
      },
      {
        type: 'category',
        name: 'retail',
        title: 'Retail',
        children: [
          { type: 'component', title: 'Consume', name: 'ConsumeIcon' },
          { type: 'component', title: 'VipConsume', name: 'VipConsumeIcon' },
          { type: 'component', title: 'Rail', name: 'RailIcon' },
          { type: 'component', title: 'IntegralDistribute', name: 'IntegralDistributeIcon' },
          { type: 'component', title: 'Integral', name: 'IntegralIcon' },
          { type: 'component', title: 'Picking', name: 'PickingIcon' },
          { type: 'component', title: 'Distribution', name: 'DistributionIcon' },
          { type: 'component', title: 'Goods', name: 'GoodsIcon' },
          { type: 'component', title: 'WarehousePre', name: 'WarehousePreIcon' },
          { type: 'component', title: 'Warehouse', name: 'WarehouseIcon' },
          { type: 'component', title: 'Inventory', name: 'InventoryIcon' },
          { type: 'component', title: 'Replenishment', name: 'ReplenishmentIcon' },
          { type: 'component', title: 'ShelfUp', name: 'ShelfUpIcon' },
          { type: 'component', title: 'ProcessMode', name: 'ProcessModeIcon' },
          { type: 'component', title: 'GoodsSearch', name: 'GoodsSearchIcon' },
          { type: 'component', title: 'PickingGuidance', name: 'PickingGuidanceIcon' },
          { type: 'component', title: 'PickingPath', name: 'PickingPathIcon' },
          { type: 'component', title: 'Path', name: 'PathIcon' },
          { type: 'component', title: 'Management', name: 'ManagementIcon' },
          { type: 'component', title: 'Overtime', name: 'OvertimeIcon' },
          { type: 'component', title: 'SalesReturn', name: 'SalesReturnIcon' },
          { type: 'component', title: 'ManagementStockout', name: 'ManagementStockoutIcon' },
          { type: 'component', title: 'Operation', name: 'OperationIcon' },
          { type: 'component', title: 'Marketing', name: 'MarketingIcon' },
          { type: 'component', title: 'WarehouseInto', name: 'WarehouseIntoIcon' },
          { type: 'component', title: 'OutOfWarehouse', name: 'OutOfWarehouseIcon' },
          { type: 'component', title: 'Scale', name: 'ScaleIcon' },
          { type: 'component', title: 'ToggleWarehouseY', name: 'ToggleWarehouseYIcon' },
          { type: 'component', title: 'Marketplace', name: 'MarketplaceIcon' },
          { type: 'component', title: 'ToggleWarehouseX', name: 'ToggleWarehouseXIcon' },
          { type: 'component', title: 'AmountDollar', name: 'AmountDollarIcon' },
          { type: 'component', title: 'Shelf', name: 'ShelfIcon' },
          { type: 'component', title: 'Incubator', name: 'IncubatorIcon' },
        ],
      },
      {
        type: 'category',
        name: 'file',
        title: 'File',
        children: [
          { type: 'component', title: 'WorkOrder', name: 'WorkOrderIcon' },
          { type: 'component', title: 'WorkOrderAppointment', name: 'WorkOrderAppointmentIcon' },
          { type: 'component', title: 'WorkOrderCheck', name: 'WorkOrderCheckIcon' },
          { type: 'component', title: 'Order', name: 'OrderIcon' },
          { type: 'component', title: 'OrderClose', name: 'OrderCloseIcon' },
          { type: 'component', title: 'OrderIntegral', name: 'OrderIntegralIcon' },
          { type: 'component', title: 'OrderAbnormal', name: 'OrderAbnormalIcon' },
          { type: 'component', title: 'OrderDone', name: 'OrderDoneIcon' },
          { type: 'component', title: 'OrderEdit', name: 'OrderEditIcon' },
          { type: 'component', title: 'Crowd', name: 'CrowdIcon' },
          { type: 'component', title: 'User', name: 'UserIcon' },
          { type: 'component', title: 'UserPortrayal', name: 'UserPortrayalIcon' },
          { type: 'component', title: 'BlackList', name: 'BlackListIcon' },
          { type: 'component', title: 'WhiteList', name: 'WhiteListIcon' },
          { type: 'component', title: 'UserSilence', name: 'UserSilenceIcon' },
          { type: 'component', title: 'UserActive', name: 'UserActiveIcon' },
          { type: 'component', title: 'UserLeave', name: 'UserLeaveIcon' },
          { type: 'component', title: 'UserAll', name: 'UserAllIcon' },
          { type: 'component', title: 'UserNew', name: 'UserNewIcon' },
          { type: 'component', title: 'Report', name: 'ReportIcon' },
          { type: 'component', title: 'Contract', name: 'ContractIcon' },
          { type: 'component', title: 'ContractExclamation', name: 'ContractExclamationIcon' },
          { type: 'component', title: 'ContractAcross', name: 'ContractAcrossIcon' },
          { type: 'component', title: 'ComputerExclamation', name: 'ComputerExclamationIcon' },
          { type: 'component', title: 'ComputerAcross', name: 'ComputerAcrossIcon' },
          { type: 'component', title: 'Attachments', name: 'AttachmentsIcon' },
          { type: 'component', title: 'FileMovie', name: 'FileMovieIcon' },
          { type: 'component', title: 'WorkOrderInfo', name: 'WorkOrderInfoIcon' },
          { type: 'component', title: 'FileImport', name: 'FileImportIcon' },
          { type: 'component', title: 'FileCsv', name: 'FileCsvIcon' },
          { type: 'component', title: 'FileRar', name: 'FileRarIcon' },
          { type: 'component', title: 'FilePpt', name: 'FilePptIcon' },
          { type: 'component', title: 'FilePdf', name: 'FilePdfIcon' },
          { type: 'component', title: 'FileMov', name: 'FileMovIcon' },
          { type: 'component', title: 'FileMp3', name: 'FileMp3Icon' },
          { type: 'component', title: 'FileMp4', name: 'FileMp4Icon' },
          { type: 'component', title: 'FileDoc', name: 'FileDocIcon' },
          { type: 'component', title: 'FileCdr', name: 'FileCdrIcon' },
          { type: 'component', title: 'FileAvi', name: 'FileAviIcon' },
          { type: 'component', title: 'FileTxt', name: 'FileTxtIcon' },
          { type: 'component', title: 'FilePng', name: 'FilePngIcon' },
          { type: 'component', title: 'FileJpg', name: 'FileJpgIcon' },
          { type: 'component', title: 'FileZip', name: 'FileZipIcon' },
          { type: 'component', title: 'FileXls', name: 'FileXlsIcon' },
          { type: 'component', title: 'WorkOrderAbnormal', name: 'WorkOrderAbnormalIcon' },
          { type: 'component', title: 'WorkingOdd', name: 'WorkingOddIcon' },
        ],
      },
      {
        type: 'category',
        name: 'toggle',
        title: 'Toggle',
        children: [
          { type: 'component', title: 'CircleStarRegular', name: 'CircleStarRegularIcon' },
          { type: 'component', title: 'CircleCloseRegular', name: 'CircleCloseRegularIcon' },
          { type: 'component', title: 'CircleReduceRegular', name: 'CircleReduceRegularIcon' },
          { type: 'component', title: 'StarRegular', name: 'StarRegularIcon' },
          { type: 'component', title: 'VolumeMuteRegular', name: 'VolumeMuteRegularIcon' },
          { type: 'component', title: 'Locked', name: 'LockedIcon' },
          { type: 'component', title: 'Unlocked', name: 'UnlockedIcon' },
          { type: 'component', title: 'VolumeRegular', name: 'VolumeRegularIcon' },
          { type: 'component', title: 'RemindOffRegular', name: 'RemindOffRegularIcon' },
        ],
      },
    ],
  },
  {
    type: 'style',
    name: 'filled',
    title: 'Solid',
    children: [
      {
        type: 'category',
        name: 'Navigation',
        title: 'Navigation',
        children: [
          { type: 'component', title: 'HomeFilled', name: 'HomeFilledIcon' },
          { type: 'component', title: 'AppsFilled', name: 'AppsFilledIcon' },
          { type: 'component', title: 'TriangleDownFilled', name: 'TriangleDownFilledIcon' },
          { type: 'component', title: 'TriangleLeftFilled', name: 'TriangleLeftFilledIcon' },
          { type: 'component', title: 'TriangleRightFilled', name: 'TriangleRightFilledIcon' },
          { type: 'component', title: 'ShellWindowMaximizeFilled', name: 'ShellWindowMaximizeFilledIcon' },
          { type: 'component', title: 'TriangleUpFilled', name: 'TriangleUpFilledIcon' },
          { type: 'component', title: 'SortFilled', name: 'SortFilledIcon' },
          { type: 'component', title: 'UpFilled', name: 'UpFilledIcon' },
          { type: 'component', title: 'DownFilled', name: 'DownFilledIcon' },
          { type: 'component', title: 'LeftFilled', name: 'LeftFilledIcon' },
          { type: 'component', title: 'DoubleArrowUpFilled', name: 'DoubleArrowUpFilledIcon' },
          { type: 'component', title: 'DoubleArrowDownFilled', name: 'DoubleArrowDownFilledIcon' },
          { type: 'component', title: 'DoubleArrowLeftFilled', name: 'DoubleArrowLeftFilledIcon' },
          { type: 'component', title: 'DoubleArrowRightFilled', name: 'DoubleArrowRightFilledIcon' },
          { type: 'component', title: 'ArrowUpFilled', name: 'ArrowUpFilledIcon' },
          { type: 'component', title: 'ArrowDownFilled', name: 'ArrowDownFilledIcon' },
          { type: 'component', title: 'ArrowLeftFilled', name: 'ArrowLeftFilledIcon' },
          { type: 'component', title: 'MenuThwartwiseFilled', name: 'MenuThwartwiseFilledIcon' },
          { type: 'component', title: 'Menu2Filled', name: 'Menu2FilledIcon' },
          { type: 'component', title: 'ArrowRightFilled', name: 'ArrowRightFilledIcon' },
          { type: 'component', title: 'MenuEndwaysFilled', name: 'MenuEndwaysFilledIcon' },
          { type: 'component', title: 'CloseSmallFilled', name: 'CloseSmallFilledIcon' },
          { type: 'component', title: 'OpenNewFilled', name: 'OpenNewFilledIcon' },
          { type: 'component', title: 'ShellWindowMinimizeFilled', name: 'ShellWindowMinimizeFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Notice',
        title: 'Notice',
        children: [
          { type: 'component', title: 'RemindCloseFilled', name: 'RemindCloseFilledIcon' },
          { type: 'component', title: 'WifiAbnormalFilled', name: 'WifiAbnormalFilledIcon' },
          { type: 'component', title: 'QuestionFilled', name: 'QuestionFilledIcon' },
          { type: 'component', title: 'RemindFilled', name: 'RemindFilledIcon' },
          { type: 'component', title: 'AddOneFilled', name: 'AddOneFilledIcon' },
          { type: 'component', title: 'CheckFilled', name: 'CheckFilledIcon' },
          { type: 'component', title: 'CircleMoreFilled', name: 'CircleMoreFilledIcon' },
          { type: 'component', title: 'MoreFilled', name: 'MoreFilledIcon' },
          { type: 'component', title: 'MinusFilled', name: 'MinusFilledIcon' },
          { type: 'component', title: 'CircleAddFilled', name: 'CircleAddFilledIcon' },
          { type: 'component', title: 'TriangleWarningFilled', name: 'TriangleWarningFilledIcon' },
          { type: 'component', title: 'ExclamationFilled', name: 'ExclamationFilledIcon' },
          { type: 'component', title: 'CircleInformationFilled', name: 'CircleInformationFilledIcon' },
          { type: 'component', title: 'CircleCloseFilled', name: 'CircleCloseFilledIcon' },
          { type: 'component', title: 'CircleStarFilled', name: 'CircleStarFilledIcon' },
          { type: 'component', title: 'CircleSucceedFilled', name: 'CircleSucceedFilledIcon' },
          { type: 'component', title: 'CircleWarningFilled', name: 'CircleWarningFilledIcon' },
          { type: 'component', title: 'StarFilled', name: 'StarFilledIcon' },
          { type: 'component', title: 'CircleHelpFilled', name: 'CircleHelpFilledIcon' },
          { type: 'component', title: 'DisableFilled', name: 'DisableFilledIcon' },
          { type: 'component', title: 'WifiFilled', name: 'WifiFilledIcon' },
          { type: 'component', title: 'WifiCloseFilled', name: 'WifiCloseFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Action',
        title: 'Action',
        children: [
          { type: 'component', title: 'ClearFilled', name: 'ClearFilledIcon' },
          { type: 'component', title: 'PinFilled', name: 'PinFilledIcon' },
          { type: 'component', title: 'ThumbDownFilled', name: 'ThumbDownFilledIcon' },
          { type: 'component', title: 'ThumbUpFilled', name: 'ThumbUpFilledIcon' },
          { type: 'component', title: 'SendFilled', name: 'SendFilledIcon' },
          { type: 'component', title: 'PinPreFilled', name: 'PinPreFilledIcon' },
          { type: 'component', title: 'ViewFilled', name: 'ViewFilledIcon' },
          { type: 'component', title: 'FilterFilled', name: 'FilterFilledIcon' },
          { type: 'component', title: 'SearchFilled', name: 'SearchFilledIcon' },
          { type: 'component', title: 'UrgencyFilled', name: 'UrgencyFilledIcon' },
          { type: 'component', title: 'ClothesFilled', name: 'ClothesFilledIcon' },
          { type: 'component', title: 'MicrophoneFilled', name: 'MicrophoneFilledIcon' },
          { type: 'component', title: 'BatchAddFilled', name: 'BatchAddFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'Data',
        title: 'Data',
        children: [
          { type: 'component', title: 'LightningFilled', name: 'LightningFilledIcon' },
          { type: 'component', title: 'PieTwoFilled', name: 'PieTwoFilledIcon' },
          { type: 'component', title: 'DataFilled', name: 'DataFilledIcon' },
          { type: 'component', title: 'PercentFilled', name: 'PercentFilledIcon' },
          { type: 'component', title: 'LineChartFilled', name: 'LineChartFilledIcon' },
          { type: 'component', title: 'TreeFilled', name: 'TreeFilledIcon' },
          { type: 'component', title: 'ThermoDynamicFilled', name: 'ThermoDynamicFilledIcon' },
          { type: 'component', title: 'MeasureFilled', name: 'MeasureFilledIcon' },
          { type: 'component', title: 'CompilingFilled', name: 'CompilingFilledIcon' },
          { type: 'component', title: 'AreaChartFilled', name: 'AreaChartFilledIcon' },
          { type: 'component', title: 'BarFilled', name: 'BarFilledIcon' },
          { type: 'component', title: 'ColumnFilled', name: 'ColumnFilledIcon' },
          { type: 'component', title: 'ColumnLineFilled', name: 'ColumnLineFilledIcon' },
          { type: 'component', title: 'WordCloudFilled', name: 'WordCloudFilledIcon' },
          { type: 'component', title: 'TableFilled', name: 'TableFilledIcon' },
          { type: 'component', title: 'PieOneFilled', name: 'PieOneFilledIcon' },
          { type: 'component', title: 'AnnularFilled', name: 'AnnularFilledIcon' },
          { type: 'component', title: 'RadarChartFilled', name: 'RadarChartFilledIcon' },
          { type: 'component', title: 'DataScreenFilled', name: 'DataScreenFilledIcon' },
          { type: 'component', title: 'ConstituteFilled', name: 'ConstituteFilledIcon' },
          { type: 'component', title: 'DatabaseFilled', name: 'DatabaseFilledIcon' },
          { type: 'component', title: 'DecimalFilled', name: 'DecimalFilledIcon' },
          { type: 'component', title: 'ScatterDiagramFilled', name: 'ScatterDiagramFilledIcon' },
          { type: 'component', title: 'NumberFilled', name: 'NumberFilledIcon' },
        ],
      },
      {
        type: 'category',
        name: 'common',
        title: 'Common',
        children: [
          { type: 'component', title: 'CheckCorrectFilled', name: 'CheckCorrectFilledIcon' },
          { type: 'component', title: 'LocationFilled', name: 'LocationFilledIcon' },
          { type: 'component', title: 'RemindOffFilled', name: 'RemindOffFilledIcon' },
          { type: 'component', title: 'SuspendFilled', name: 'SuspendFilledIcon' },
          { type: 'component', title: 'PlayFilled', name: 'PlayFilledIcon' },
          { type: 'component', title: 'CircleReduceFilled', name: 'CircleReduceFilledIcon' },
          { type: 'component', title: 'VolumeMuteFilled', name: 'VolumeMuteFilledIcon' },
          { type: 'component', title: 'CheckDisabledFilled', name: 'CheckDisabledFilledIcon' },
          { type: 'component', title: 'VolumeFilled', name: 'VolumeFilledIcon' },
        ],
      },
    ],
  },
]
