export default [
  {
    type: 'style',
    name: 'outline',
    title: 'Outline',
    children: [
      {
        type: 'category',
        name: 'nav',
        title: 'Nav',
        children: [
          { type: 'component', name: 'LeftBig' },
          { type: 'component', name: 'RightBig' },
          { type: 'component', name: 'Up' },
          { type: 'component', name: 'Down' },
          { type: 'component', name: 'Left' },
          { type: 'component', name: 'Right' },
          { type: 'component', name: 'DoubleArrowUp' },
          { type: 'component', name: 'DoubleArrowDown' },
          { type: 'component', name: 'DoubleArrowLeft' },
          { type: 'component', name: 'DoubleArrowRight' },
          { type: 'component', name: 'ArrowUp' },
          { type: 'component', name: 'ArrowDown' },
          { type: 'component', name: 'Home' },
          { type: 'component', name: 'ArrowLeft' },
          { type: 'component', name: 'MenuThwartwise' },
          { type: 'component', name: 'Menu2' },
          { type: 'component', name: 'ArrowRight' },
          { type: 'component', name: 'MenuEndways' },
          { type: 'component', name: 'CloseSmall' },
          { type: 'component', name: 'Apps' },
          { type: 'component', name: 'OpenNew' },
          { type: 'component', name: 'ShellWindowMaximize' },
          { type: 'component', name: 'ShellWindowMinimize' },
        ],
      },
      {
        type: 'category',
        name: 'common',
        title: 'Common',
        children: [
          { type: 'component', name: 'TriangleRight' },
          { type: 'component', name: 'Sort' },
          { type: 'component', name: 'TriangleUp' },
          { type: 'component', name: 'TriangleDown' },
          { type: 'component', name: 'Question' },
          { type: 'component', name: 'CircleInformation' },
          { type: 'component', name: 'TriangleWarning' },
          { type: 'component', name: 'Wifi' },
          { type: 'component', name: 'WifiAbnormal' },
          { type: 'component', name: 'WifiClose' },
          { type: 'component', name: 'CircleMore' },
          { type: 'component', name: 'More' },
          { type: 'component', name: 'CircleHelp' },
          { type: 'component', name: 'RemindClose' },
          { type: 'component', name: 'CircleWarning' },
          { type: 'component', name: 'Exclamation' },
          { type: 'component', name: 'AddChat2' },
          { type: 'component', name: 'Drag' },
          { type: 'component', name: 'Phone' },
          { type: 'component', name: 'RefreshDone' },
          { type: 'component', name: 'RefreshDoing' },
          { type: 'component', name: 'Refresh' },
          { type: 'component', name: 'Clockwise90' },
          { type: 'component', name: 'Decimal' },
          { type: 'component', name: 'No' },
          { type: 'component', name: 'ScatterDiagram' },
          { type: 'component', name: 'PieTwo' },
          { type: 'component', name: 'Lock' },
          { type: 'component', name: 'Unlock' },
          { type: 'component', name: 'SandGlass' },
          { type: 'component', name: 'Time' },
          { type: 'component', name: 'Leaf' },
          { type: 'component', name: 'PackingBox' },
          { type: 'component', name: 'Amount' },
          { type: 'component', name: 'Purse' },
          { type: 'component', name: 'Fire' },
          { type: 'component', name: 'Gift' },
          { type: 'component', name: 'Label' },
          { type: 'component', name: 'Location' },
          { type: 'component', name: 'Park' },
          { type: 'component', name: 'Hospital' },
          { type: 'component', name: 'School' },
          { type: 'component', name: 'Shopping' },
          { type: 'component', name: 'Basket' },
          { type: 'component', name: 'Berth' },
          { type: 'component', name: 'Soup' },
          { type: 'component', name: 'Bun' },
          { type: 'component', name: 'StapleFood' },
          { type: 'component', name: 'Bunch' },
          { type: 'component', name: 'Chips' },
          { type: 'component', name: 'Order' },
          { type: 'component', name: 'Chef' },
          { type: 'component', name: 'Sunny' },
          { type: 'component', name: 'Cloudy' },
          { type: 'component', name: 'LightRain' },
          { type: 'component', name: 'HeavyRain' },
          { type: 'component', name: 'LightSnow' },
          { type: 'component', name: 'HeavySnow' },
          { type: 'component', name: 'Haze' },
          { type: 'component', name: 'Sand' },
          { type: 'component', name: 'Music' },
          { type: 'component', name: 'Computer' },
          { type: 'component', name: 'Building' },
          { type: 'component', name: 'Comments' },
          { type: 'component', name: 'Coupon' },
          { type: 'component', name: 'Checkstand' },
          { type: 'component', name: 'Store' },
          { type: 'component', name: 'House' },
          { type: 'component', name: 'Calendar' },
          { type: 'component', name: 'Stamp' },
          { type: 'component', name: 'Picture' },
          { type: 'component', name: 'PictureOff' },
          { type: 'component', name: 'QrCode' },
          { type: 'component', name: 'Gather' },
          { type: 'component', name: 'Puzzle' },
          { type: 'component', name: 'BarCode' },
          { type: 'component', name: 'Handshake' },
          { type: 'component', name: 'Flag' },
          { type: 'component', name: 'Motorcycle' },
          { type: 'component', name: 'Shield' },
          { type: 'component', name: 'Vip' },
          { type: 'component', name: 'Calculator' },
          { type: 'component', name: 'Equipment' },
          { type: 'component', name: 'OnlineGateway' },
          { type: 'component', name: 'OfflineGateway' },
          { type: 'component', name: 'Monitoring' },
          { type: 'component', name: 'Promotion' },
          { type: 'component', name: 'Service' },
          { type: 'component', name: 'ShoppingCart' },
          { type: 'component', name: 'Camera' },
          { type: 'component', name: 'Earth' },
          { type: 'component', name: 'EmailSend' },
          { type: 'component', name: 'PushMgt' },
          { type: 'component', name: 'New' },
          { type: 'component', name: 'Deal' },
          { type: 'component', name: 'Incubator' },
          { type: 'component', name: 'MiniApp' },
          { type: 'component', name: 'Shelf' },
          { type: 'component', name: 'PickingAll' },
          { type: 'component', name: 'WorkingOdd' },
          { type: 'component', name: 'WorkOrderAbnormal' },
          { type: 'component', name: 'FileAvi' },
          { type: 'component', name: 'FileTxt' },
          { type: 'component', name: 'FilePng' },
          { type: 'component', name: 'FileJpg' },
          { type: 'component', name: 'FileZip' },
          { type: 'component', name: 'FileXls' },
          { type: 'component', name: 'FileRar' },
          { type: 'component', name: 'FilePpt' },
          { type: 'component', name: 'FilePdf' },
          { type: 'component', name: 'FileMov' },
          { type: 'component', name: 'FileMp3' },
          { type: 'component', name: 'FileMp4' },
          { type: 'component', name: 'FileDoc' },
          { type: 'component', name: 'FileCdr' },
          { type: 'component', name: 'FileCsv' },
        ],
      },
      {
        type: 'category',
        name: 'notice',
        title: 'Notice',
        children: [
          { type: 'component', name: 'Remind' },
          { type: 'component', name: 'AddOne' },
          { type: 'component', name: 'Minus' },
          { type: 'component', name: 'Disable' },
          { type: 'component', name: 'CircleClose' },
          { type: 'component', name: 'CircleStar' },
          { type: 'component', name: 'CircleAdd' },
          { type: 'component', name: 'CircleSucceed' },
          { type: 'component', name: 'Check' },
        ],
      },
      {
        type: 'category',
        name: 'action',
        title: 'Action',
        children: [
          { type: 'component', name: 'Clear' },
          { type: 'component', name: 'MoveUp' },
          { type: 'component', name: 'MoveDown' },
          { type: 'component', name: 'Undo' },
          { type: 'component', name: 'ThumbDown' },
          { type: 'component', name: 'ThumbUp' },
          { type: 'component', name: 'Pin' },
          { type: 'component', name: 'PinPre' },
          { type: 'component', name: 'View' },
          { type: 'component', name: 'ViewOff' },
          { type: 'component', name: 'InfuseOne' },
          { type: 'component', name: 'Download' },
          { type: 'component', name: 'Uploading' },
          { type: 'component', name: 'ToTop' },
          { type: 'component', name: 'Top' },
          { type: 'component', name: 'Goto' },
          { type: 'component', name: 'ToBottom' },
          { type: 'component', name: 'Link' },
          { type: 'component', name: 'Unlink' },
          { type: 'component', name: 'InfuseTwo' },
          { type: 'component', name: 'ExportTwo' },
          { type: 'component', name: 'Control' },
          { type: 'component', name: 'Decorate' },
          { type: 'component', name: 'FormatPainter' },
          { type: 'component', name: 'CopyOne' },
          { type: 'component', name: 'Delete' },
          { type: 'component', name: 'MapLocation' },
          { type: 'component', name: 'Scan' },
          { type: 'component', name: 'Filter' },
          { type: 'component', name: 'Switch' },
          { type: 'component', name: 'Share' },
          { type: 'component', name: 'SettingSearch' },
          { type: 'component', name: 'Setting' },
          { type: 'component', name: 'Swerve' },
          { type: 'component', name: 'Urgency' },
          { type: 'component', name: 'Save' },
          { type: 'component', name: 'SaveAs' },
          { type: 'component', name: 'Print' },
          { type: 'component', name: 'Power' },
          { type: 'component', name: 'AmountUp' },
          { type: 'component', name: 'AmountDown' },
          { type: 'component', name: 'Submit' },
          { type: 'component', name: 'Search' },
          { type: 'component', name: 'Checkbox' },
          { type: 'component', name: 'Export' },
          { type: 'component', name: 'CheckCorrect' },
          { type: 'component', name: 'CheckDisabled' },
          { type: 'component', name: 'RadioUnselected' },
          { type: 'component', name: 'RadioSelected' },
          { type: 'component', name: 'Translate' },
          { type: 'component', name: 'Clothes' },
          { type: 'component', name: 'Paste' },
          { type: 'component', name: 'Rollback' },
          { type: 'component', name: 'BatchCheck' },
          { type: 'component', name: 'BatchAdd' },
          { type: 'component', name: 'Microphone' },
          { type: 'component', name: 'AddChat' },
          { type: 'component', name: 'SortDefault' },
          { type: 'component', name: 'SortA2Z' },
          { type: 'component', name: 'SortZ2A' },
        ],
      },
      {
        type: 'category',
        name: 'control',
        title: 'Control',
        children: [
          { type: 'component', name: 'ScreenFull' },
          { type: 'component', name: 'ScreenOff' },
          { type: 'component', name: 'Move' },
          { type: 'component', name: 'Pointer' },
          { type: 'component', name: 'Coverage' },
          { type: 'component', name: 'SurfaceTop' },
          { type: 'component', name: 'SurfaceLeft' },
          { type: 'component', name: 'SurfaceRight' },
          { type: 'component', name: 'Anticlockwise90' },
          { type: 'component', name: 'CopyTwo' },
          { type: 'component', name: 'Hight' },
          { type: 'component', name: 'HightLessen' },
          { type: 'component', name: 'Width' },
          { type: 'component', name: 'VerticalSplit' },
          { type: 'component', name: 'VerticalCenter' },
          { type: 'component', name: 'CenterHorizontally' },
          { type: 'component', name: 'TopAlign' },
          { type: 'component', name: 'BottomAlign' },
          { type: 'component', name: 'FrontSquare' },
          { type: 'component', name: 'BackSquare' },
          { type: 'component', name: 'LeftSquare' },
          { type: 'component', name: 'RightSquare' },
          { type: 'component', name: 'Text' },
          { type: 'component', name: 'Keyboard' },
          { type: 'component', name: 'ZoomOut' },
          { type: 'component', name: 'ZoomIn' },
          { type: 'component', name: 'Volume' },
          { type: 'component', name: 'VolumeUp' },
          { type: 'component', name: 'VolumeDown' },
          { type: 'component', name: 'Play' },
          { type: 'component', name: 'Stop' },
          { type: 'component', name: 'Suspend' },
          { type: 'component', name: 'FitScreen' },
          { type: 'component', name: 'RotationLeft' },
          { type: 'component', name: 'OneToOne' },
          { type: 'component', name: 'AlignTxtBoth' },
          { type: 'component', name: 'AlignTxtLeft' },
          { type: 'component', name: 'AlignTxtRight' },
          { type: 'component', name: 'AlignTxtCenter' },
          { type: 'component', name: 'VolumeMute' },
          { type: 'component', name: 'SurfaceFront' },
          { type: 'component', name: 'DensityL' },
          { type: 'component', name: 'DensityM' },
          { type: 'component', name: 'DensityS' },
          { type: 'component', name: 'Find' },
          { type: 'component', name: 'RowHeightS' },
        ],
      },
      {
        type: 'category',
        name: 'data',
        title: 'Data',
        children: [
          { type: 'component', name: 'LineChart' },
          { type: 'component', name: 'AreaChart' },
          { type: 'component', name: 'Bar' },
          { type: 'component', name: 'Column' },
          { type: 'component', name: 'WordCloud' },
          { type: 'component', name: 'Tree' },
          { type: 'component', name: 'Table' },
          { type: 'component', name: 'PieOne' },
          { type: 'component', name: 'Annular' },
          { type: 'component', name: 'Thermodynamic' },
          { type: 'component', name: 'Lightning' },
          { type: 'component', name: 'Measure' },
          { type: 'component', name: 'Data' },
          { type: 'component', name: 'RadarChart' },
          { type: 'component', name: 'Compiling' },
          { type: 'component', name: 'DataScreen' },
          { type: 'component', name: 'Constitute' },
          { type: 'component', name: 'Percent' },
          { type: 'component', name: 'Database' },
        ],
      },
      {
        type: 'category',
        name: 'retail',
        title: 'Retail',
        children: [
          { type: 'component', name: 'Consume' },
          { type: 'component', name: 'VipConsume' },
          { type: 'component', name: 'Rail' },
          { type: 'component', name: 'IntegralDistribute' },
          { type: 'component', name: 'Integral' },
          { type: 'component', name: 'Picking' },
          { type: 'component', name: 'Distribution' },
          { type: 'component', name: 'Goods' },
          { type: 'component', name: 'WarehousePre' },
          { type: 'component', name: 'Warehouse' },
          { type: 'component', name: 'Inventory' },
          { type: 'component', name: 'Replenishment' },
          { type: 'component', name: 'ShelfUp' },
          { type: 'component', name: 'ProcessMode' },
          { type: 'component', name: 'GoodsSearch' },
          { type: 'component', name: 'PickingGuidance' },
          { type: 'component', name: 'PickingPath' },
          { type: 'component', name: 'Path' },
          { type: 'component', name: 'Management' },
          { type: 'component', name: 'Overtime' },
          { type: 'component', name: 'SalesReturn' },
          { type: 'component', name: 'ManagementStockout' },
          { type: 'component', name: 'Operation' },
          { type: 'component', name: 'Marketing' },
          { type: 'component', name: 'WarehouseInto' },
          { type: 'component', name: 'OutOfWarehouse' },
          { type: 'component', name: 'Scale' },
          { type: 'component', name: 'ToggleWarehouseY' },
          { type: 'component', name: 'Marketplace' },
          { type: 'component', name: 'ToggleWarehouseX' },
        ],
      },
      {
        type: 'category',
        name: 'file',
        title: 'File',
        children: [
          { type: 'component', name: 'WorkOrder' },
          { type: 'component', name: 'WorkOrderAppointment' },
          { type: 'component', name: 'WorkOrderCheck' },
          { type: 'component', name: 'OrderClose' },
          { type: 'component', name: 'OrderIntegral' },
          { type: 'component', name: 'OrderAbnormal' },
          { type: 'component', name: 'OrderDone' },
          { type: 'component', name: 'OrderEdit' },
          { type: 'component', name: 'Crowd' },
          { type: 'component', name: 'User' },
          { type: 'component', name: 'UserPortrayal' },
          { type: 'component', name: 'BlackList' },
          { type: 'component', name: 'WhiteList' },
          { type: 'component', name: 'UserSilence' },
          { type: 'component', name: 'UserActive' },
          { type: 'component', name: 'UserLeave' },
          { type: 'component', name: 'UserAll' },
          { type: 'component', name: 'UserNew' },
          { type: 'component', name: 'Report' },
          { type: 'component', name: 'Contract' },
          { type: 'component', name: 'ContractExclamation' },
          { type: 'component', name: 'ContractAcross' },
          { type: 'component', name: 'ComputerExclamation' },
          { type: 'component', name: 'ComputerAcross' },
          { type: 'component', name: 'Attachments' },
          { type: 'component', name: 'WorkOrderInfo' },
          { type: 'component', name: 'FileImport' },
        ],
      },
      {
        type: 'category',
        name: 'toggle',
        title: 'Toggle',
        children: [
          { type: 'component', name: 'CircleWarningRegular' },
          { type: 'component', name: 'CircleSucceedRegular' },
          { type: 'component', name: 'CircleHelpRegular' },
          { type: 'component', name: 'CircleStarRegular' },
          { type: 'component', name: 'CircleCloseRegular' },
          { type: 'component', name: 'CircleAddRegular' },
          { type: 'component', name: 'CircleMoreRegular' },
          { type: 'component', name: 'StarRegular' },
          { type: 'component', name: 'ThumbUpRegular' },
          { type: 'component', name: 'ThumbDownRegular' },
          { type: 'component', name: 'VolumeMuteRegular' },
          { type: 'component', name: 'Locked' },
          { type: 'component', name: 'Unlocked' },
          { type: 'component', name: 'VolumeRegular' },
          { type: 'component', name: 'RemindRegular' },
          { type: 'component', name: 'RemindOffRegular' },
          { type: 'component', name: 'PinRegular' },
          { type: 'component', name: 'PinPreRegular' },
        ],
      },
    ],
  },
  {
    type: 'style',
    name: 'filled',
    title: 'Solid',
    children: [
      {
        type: 'category',
        name: 'toggle',
        title: 'Toggle',
        children: [
          { type: 'component', name: 'CircleWarningFilled' },
          { type: 'component', name: 'CircleSucceedFilled' },
          { type: 'component', name: 'CircleHelpFilled' },
          { type: 'component', name: 'CircleStarFilled' },
          { type: 'component', name: 'CircleCloseFilled' },
          { type: 'component', name: 'CircleAddFilled' },
          { type: 'component', name: 'CircleMoreFilled' },
          { type: 'component', name: 'StarFilled' },
          { type: 'component', name: 'PinFilled' },
          { type: 'component', name: 'PinPreFilled' },
          { type: 'component', name: 'CheckCorrectFilled' },
          { type: 'component', name: 'CheckDisabledFilled' },
          { type: 'component', name: 'ThumbUpFilled' },
          { type: 'component', name: 'ThumbDownFilled' },
          { type: 'component', name: 'VolumeMuteFilled' },
          { type: 'component', name: 'RemindFilled' },
          { type: 'component', name: 'VolumeFilled' },
          { type: 'component', name: 'RemindOffFilled' },
          { type: 'component', name: 'PlayFilled' },
          { type: 'component', name: 'SuspendFilled' },
          { type: 'component', name: 'LocationFilled' },
        ],
      },
    ],
  },
]
